name: FTP Test

on:
  workflow_dispatch:

jobs:
  ftp-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create test.txt file
        run: echo "This is a test file." > test.txt

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # 必要なFTP接続情報を入力
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_ROOT }}
          # local-dir: notion  # 必要な場合、dist フォルダを指定
          local-dir: .  # 現在のディレクトリを指定