name: FTP Test

on:
  workflow_dispatch:

jobs:
  ftp-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # 必要なFTP接続情報を入力
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_REMOTE_ROOT }}
          # local-dir: ./dist/
          # テスト用のファイルを作成
          # local-dir: .
          files: |
            test.txt: This is a test file.